// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXOpmH51EM0yjOCkpZATNDnw8dRk3p3nI',
    appId: '1:288729272551:web:47f2a86b972526f288d242',
    messagingSenderId: '288729272551',
    projectId: 'courtcall-app',
    authDomain: 'courtcall-app.firebaseapp.com',
    storageBucket: 'courtcall-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtIU9TfnnVR5XCaKpZp-9FpLxPMD_Yy1k',
    appId: '1:288729272551:android:458be720feeb14f188d242',
    messagingSenderId: '288729272551',
    projectId: 'courtcall-app',
    storageBucket: 'courtcall-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeUsvcUehbJuXLgBPVsFvmLASXiCxYFa0',
    appId: '1:288729272551:ios:028ec837d5abd22688d242',
    messagingSenderId: '288729272551',
    projectId: 'courtcall-app',
    storageBucket: 'courtcall-app.firebasestorage.app',
    iosBundleId: 'com.example.courtcall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeUsvcUehbJuXLgBPVsFvmLASXiCxYFa0',
    appId: '1:288729272551:ios:028ec837d5abd22688d242',
    messagingSenderId: '288729272551',
    projectId: 'courtcall-app',
    storageBucket: 'courtcall-app.firebasestorage.app',
    iosBundleId: 'com.example.courtcall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXOpmH51EM0yjOCkpZATNDnw8dRk3p3nI',
    appId: '1:288729272551:web:5b654620cb0d365088d242',
    messagingSenderId: '288729272551',
    projectId: 'courtcall-app',
    authDomain: 'courtcall-app.firebaseapp.com',
    storageBucket: 'courtcall-app.firebasestorage.app',
  );

}